/**
 * @file main.cpp
 * @brief TinyForge example — vibration anomaly detection (7.1).
 * Mirrors FlexNN/src/main.cpp structure.
 *
 * This is the firmware entry point that links against TinyForge::TinyForge
 * and a header generated by FlexNN's tinyforge-compile.
 *
 * Build (host, scalar):
 *   cmake -S . -B build && cmake --build build && ./build/main
 *
 * Cross (STM32F407, scalar):
 *   cmake -S . -B build-mcu -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/arm-cortex-m4f.cmake
 *   cmake --build build-mcu
 *
 * The model header is generated by FlexNN:
 *   external/FlexNN/build/tools/compiler/tinyforge-compile model.bin -o generated
 */
#include "tinyforge/tinyforge.h"

#if __has_include("generated/model_data.h")
#include "generated/model_data.h"
#else
// Dummy dims for host build without a model
#ifndef TINYFORGE_INPUT_DIM
#define TINYFORGE_INPUT_DIM 192
#endif
#ifndef TINYFORGE_OUTPUT_DIM
#define TINYFORGE_OUTPUT_DIM 1
#endif
#endif

int main() {
  tinyforge::Model model;
  if (model.init() != tinyforge::Status::Ok) return -1;

  int8_t input[TINYFORGE_INPUT_DIM] = {0};
  int8_t output[TINYFORGE_OUTPUT_DIM] = {0};

  // In real firmware, fill `input` from sensor (SPI accel, etc.)
  auto st = model.run(input, output);
  if (st != tinyforge::Status::Ok) return -1;

  // For anomaly detection (binary, Sigmoid), threshold at zero-point
  bool anomaly = output[0] > 0;
  (void)anomaly;
  return 0;
}
