/**
 * @file main.cpp
 * @brief Example: vibration anomaly detection (7.1 from ref/OVERVIEW.md).
 * Uses TinyForge as a library — similar to FlexNN/src/main.cpp.
 * This file is *not* part of the library; it is an example firmware main
 * that links against TinyForge::TinyForge and a generated model.
 *
 * Build:
 *   FlexNN: train → export model.bin → tinyforge-compile → TinyForge/generated/model_data.h
 *   TinyForge (host test): cmake -B build -DTINYFORGE_BUILD_EXAMPLES=ON && cmake --build build
 *   TinyForge (MCU): arm-none-eabi-gcc with -mcpu=cortex-m4 ... + CMSIS
 *
 * @author Nalin Angrish <nalin@nalinangrish.me>
 */
#include "tinyforge/tinyforge.h"

// Generated by FlexNN's compiler — not committed, gitignored
#if __has_include("generated/model_data.h")
#include "generated/model_data.h"
#else
// Dummy for host build without a model
#define TINYFORGE_INPUT_DIM 192
#define TINYFORGE_OUTPUT_DIM 1
#endif

int main() {
  tinyforge::Model model;
  auto status = model.init();
  if (status != tinyforge::Status::Ok) {
    // On MCU, blink LED or log via UART
    return -1;
  }

  // Windowed accelerometer data (192 = 64 samples * 3 axes)
  int8_t input[TINYFORGE_INPUT_DIM] = {0};
  int8_t output[TINYFORGE_OUTPUT_DIM];

  // In real firmware, fill `input` from SPI accel driver:
  //   accel_read_window(input);
  // Here we just run the model
  status = model.run(input, output);
  if (status != tinyforge::Status::Ok) return -1;

  // Binary anomaly: output logits → threshold at zero-point
  // For int8 Sigmoid model, output is quantized logit; dequantize if needed
  bool anomaly = output[0] > 0; // placeholder
  (void)anomaly;
  return 0;
}
